#     _          _   _ _____                         ___  ____
#    / \   _ __ | |_(_)  ___|__  _ __ ___ ___       / _ \|  _ \
#   / _ \ | '_ \| __| | |_ / _ \| '__/ __/ _ \_____| | | | |_) |
#  / ___ \| | | | |_| |  _| (_) | | | (_|  __/_____| |_| |  __/
# /_/   \_\_| |_|\__|_|_|  \___/|_|  \___\___|      \___/|_|

# Copyright (C) 2020-2021  ilai

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This is the message that we will show to the OPed users that aren't registered
ban-message: "Unknown OP player. Think is a mistake? Contact the server developer"

# As by using the built-in ban command, you can personalize the ban reason
ban-reason: "Unknown OP player."

# The allowed players to join the server with OP privileges
# /!\ WARNING: All OPed player that isn't on here will be banned. /!\
allowed:
  - "Player1"
  - "Player2"